#!/usr/bin/env python3
"""Generate documentation from reconciliation reports."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from rich.console import Console

from .utils.reconciliation_report import load_reconciliation_report

console = Console()

FRONTMATTER = """---
title: Validation Report
description: F5 XC API spec validation and fix report
---
"""


def _format_value(value: object) -> str:
    """Format a value for display in MDX table, escaping HTML chars and MDX braces."""
    if value is None:
        return "-"
    if isinstance(value, bool):
        str_value = "true" if value else "false"
    elif isinstance(value, (list, dict)):
        json_str = json.dumps(value)
        if len(json_str) > 50:
            json_str = f"{json_str[:47]}..."
        str_value = json_str
    else:
        str_value = str(value)
    
    # MDX-safe escaping
    str_value = (
        str_value.replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "&#124;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
    )
    return f"`{str_value}`"


def generate_fixes_page(report: dict, output_path: Path) -> None:
    lines = [
        FRONTMATTER.strip(),
        "",
        "# F5 XC API Spec Fixes Applied",
        "",
        "Validated and reconciled F5 Distributed Cloud OpenAPI specifications.",
        "",
        f"*Generated: {report.get('generated_at', 'unknown')}*",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|--------|-------|",
    ]
    
    summary = report.get("summary", {})
    lines.extend([
        f"| Specs Processed | {summary.get('processed_specs', 0)} |",
        f"| Discrepancies Received | {summary.get('discrepancies_received', 0)} |",
        f"| **Fixes Applied** | **{summary.get('fixes_applied', 0)}** |",
        f"| Failures | {summary.get('failures', 0)} |",
        "",
    ])

    fixes = report.get("fixes", [])
    if fixes:
        lines.extend([
            "## Fixes Applied",
            "",
        ])
        fixes_by_file = {}
        for fix in fixes:
            fixes_by_file.setdefault(fix["spec_file"], []).append(fix)
            
        for filename, file_fixes in sorted(fixes_by_file.items()):
            lines.extend([
                f"### {filename}",
                "",
                "| Property | Constraint | Strategy | Before | After |",
                "|----------|------------|----------|--------|-------|",
            ])
            for fix in file_fixes:
                sd = fix.get("source_discrepancy", {})
                prop = sd.get("property_name", "-")
                constraint = sd.get("constraint_type", "-")
                strategy = fix.get("strategy", "-")
                before = _format_value(fix.get("before"))
                after = _format_value(fix.get("after"))
                lines.append(f"| `{prop}` | `{constraint}` | {strategy} | {before} | {after} |")
            lines.extend([
                "",
            ])

    failures = report.get("failures", [])
    if failures:
        lines.extend([
            "## Failures",
            "",
        ])
        failures_by_file = {}
        for failure in failures:
            failures_by_file.setdefault(failure["spec_file"], []).append(failure)
            
        for filename, file_failures in sorted(failures_by_file.items()):
            lines.extend([
                f"### {filename}",
                "",
                "| Stage | Error |",
                "|-------|-------|",
            ])
            for failure in file_failures:
                stage = failure.get("stage", "-")
                err = _format_value(failure.get("error", "-"))
                lines.append(f"| {stage} | {err} |")
            lines.extend([
                "",
            ])

    lines.extend([
        "---",
        "",
        "*This page is auto-generated by the [validation pipeline](https://github.com/f5-sales-demo/api-specs/actions).*",
        ""
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as f:
        f.write("\n".join(lines))
    console.print(f"[green]Generated: {output_path}[/green]")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate documentation from reconciliation reports")
    parser.add_argument(
        "--reconciliation-report",
        type=Path,
        required=True,
        help="Path to strict reconciliation report JSON",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/en/01-validation-report.mdx"),
        help="Output path for documentation page",
    )
    args = parser.parse_args()

    console.print("[bold blue]Generating Documentation[/bold blue]")
    try:
        report = load_reconciliation_report(args.reconciliation_report)
    except Exception as e:
        console.print(f"[red]Failed to load reconciliation report: {e}[/red]")
        return 1

    generate_fixes_page(report, args.output)
    console.print("[green]Documentation generation complete[/green]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
